apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  replicas: 3
  selector:
    matchLabels:
      name: demo-service
  template:
    metadata:
      labels:
        name: demo-service
    spec:
      containers:
      - name: demo-service
        image: prometheus-demo-service:latest
        imagePullPolicy: IfNotPresent
        args:
        - -listen-address=:80
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 80
    name: demo-service
  selector:
    name: demo-service